name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Install dependencies
      run: dotnet restore --locked-mode

    - name: Build the project
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity minimal
